-- ============================================================================
-- 007 — MODERASYON: YORUM BİLDİRME + KULLANICI ENGELLEME
-- ============================================================================
-- Google Play, kullanıcı içeriği barındıran uygulamalarda üç şey ister:
--   1) uygunsuz içeriği BİLDİRME yolu,
--   2) rahatsız eden kullanıcıyı ENGELLEME yolu,
--   3) bildirimlere makul sürede karşılık veren bir MODERASYON süreci.
-- Bu dosya bunların veri tarafını kurar. (Yayın kontrol listesi E9.)
--
-- EKLENEN TABLOLAR
--   comment_reports   yorum bildirimleri (kim, hangi yorumu, hangi sebeple)
--   user_blocks       kullanıcı engelleri (kim kimi engelledi)
--
-- MEVCUT TABLOYA EKLENEN SÜTUNLAR
--   comments.hidden_at      gizlenme anı (null = görünür)
--   comments.hidden_reason  gizlenme sebebi (kısa, kişisel veri içermez)
--
-- ---------------------------------------------------------------------------
-- DEVRALMA NOTU — comments / comment_likes neden burada da tanımlanıyor?
-- ---------------------------------------------------------------------------
-- Bu iki tablo canlı veritabanında ZATEN VAR ama hiçbir migration dosyasında
-- tanımlı DEĞİL: migration düzeni kurulmadan önce elle oluşturulmuşlar. Bu,
-- şemanın bir bölümünün kayıt dışı kalması demektir; sıfırdan kurulan bir
-- veritabanında (ör. test) o tablolar hiç oluşmaz ve buraya bağlanan her şey
-- kırılır.
--
-- Bu yüzden 007 onları `create table if not exists` ile DEVRALIR:
--   • Canlı veritabanında tablo zaten olduğu için bu ifade HİÇBİR ŞEY YAPMAZ.
--     Mevcut satırlara, sütunlara ve index'lere dokunulmaz.
--   • Boş bir veritabanında tabloyu oluşturur; böylece şema artık eksiksiz
--     kayıt altındadır ve doğrulama (verify.js) bu tabloları da denetler.
--
-- ERİŞİM MODELİ: 006 ile aynı — bu tablolara YALNIZ backend (service role)
-- erişir. RLS tümünde açıktır ve HİÇBİR policy tanımlanmaz → publishable/anon
-- anahtarla erişim varsayılan olarak REDDEDİLİR (default deny).
--
-- İDEMPOTENT: Bu dosya birden çok kez güvenle çalıştırılabilir.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0) DEVRALINAN TABLOLAR — yorum sistemi (elle oluşturulmuştu, artık kayıtlı)
-- ---------------------------------------------------------------------------
-- UYARI: Buradaki tanım, canlı tabloyu DEĞİŞTİRMEZ. Canlıda tablo var, bu
-- ifade atlanır. Tanım yalnız sıfırdan kurulan veritabanları için geçerlidir
-- ve uygulama kodunun (routes/comments.js) okuduğu sütunlardan türetilmiştir.
create table if not exists public.comments (
  id         bigint generated by default as identity primary key,
  match_id   text not null,                    -- resmî sportotoMatchId (metin)
  user_id    uuid not null references auth.users(id) on delete cascade,
  text       text not null,
  parent_id  bigint references public.comments(id) on delete cascade,
  view_count integer not null default 0,
  created_at timestamptz not null default now(),
  edited_at  timestamptz
);
create index if not exists idx_comments_match on public.comments (match_id, created_at);
create index if not exists idx_comments_user  on public.comments (user_id);

create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  -- Aynı kullanıcı aynı yorumu bir kez beğenir.
  primary key (comment_id, user_id)
);
create index if not exists idx_comment_likes_user on public.comment_likes (user_id);

-- ---------------------------------------------------------------------------
-- 1) GİZLEME SÜTUNLARI — moderasyon sonucu
-- ---------------------------------------------------------------------------
-- Gizlenen yorum SİLİNMEZ. Sebebi: (a) yazarına ne olduğunu dürüstçe
-- gösterebilmek, (b) bir bildirim haksızsa geri alınabilmesi. Gizli yorum
-- listede kimseye görünmez; yalnız YAZARI kendi yorumunu "gizlendi" etiketiyle
-- görür.
alter table public.comments add column if not exists hidden_at     timestamptz;
alter table public.comments add column if not exists hidden_reason text;

create index if not exists idx_comments_visible
  on public.comments (match_id, created_at) where hidden_at is null;

-- ---------------------------------------------------------------------------
-- 2) YORUM BİLDİRİMLERİ
-- ---------------------------------------------------------------------------
-- unique (comment_id, reporter_id): aynı kullanıcı aynı yorumu bir kez bildirir.
-- Bu, otomatik gizleme eşiğinin tek kişi tarafından doldurulmasını İMKÂNSIZ
-- kılar — eşik "farklı kişi" sayısıdır, "tıklama" sayısı değil.
create table if not exists public.comment_reports (
  id          bigint generated always as identity primary key,
  comment_id  bigint not null,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  -- Sebep listesi KAPALIDIR: serbest metin sebep olarak kabul edilmez.
  reason      text not null check (reason in (
                'spam', 'hakaret', 'nefret', 'cinsel', 'siddet', 'yaniltici', 'diger')),
  -- İsteğe bağlı kısa açıklama. Kişisel veri yazılmaması için kısa tutulur.
  note        text not null default '' check (char_length(note) <= 300),
  status      text not null default 'beklemede'
              check (status in ('beklemede', 'kabul', 'ret')),
  created_at  timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid,
  unique (comment_id, reporter_id)
);
create index if not exists idx_comment_reports_open
  on public.comment_reports (created_at desc) where status = 'beklemede';
create index if not exists idx_comment_reports_comment
  on public.comment_reports (comment_id);

-- comment_id → comments(id) yabancı anahtarı KORUMALI eklenir.
-- Neden korumalı: `comments` tablosu bu migration düzeninden ÖNCE elle
-- oluşturulmuştu; canlı sütun türünün burada varsayılanla birebir aynı olduğu
-- ÖLÇÜLMEDİ. Tür uyuşmazsa kısıt eklenemez. Bunun migration'ın tamamını
-- düşürmesine izin verilmez: kısıt kurulamazsa açıkça NOTICE yazılır ve
-- bütünlük kod tarafında korunur (yorum silinince bildirimleri de silinir —
-- bkz. routes/comments.js). Sessiz kabul YOKTUR; her iki durum da loga geçer.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'comment_reports_comment_fk') then
    begin
      alter table public.comment_reports
        add constraint comment_reports_comment_fk
        foreign key (comment_id) references public.comments(id) on delete cascade;
      raise notice '007: comment_reports -> comments yabanci anahtari kuruldu.';
    exception when others then
      raise notice '007: comment_reports -> comments yabanci anahtari KURULAMADI (%). Butunluk kod tarafinda korunuyor.', sqlerrm;
    end;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 3) KULLANICI ENGELLERİ
-- ---------------------------------------------------------------------------
-- Engel TEK YÖNLÜ bir kayıttır (blocker → blocked) ama görünürlükte ÇİFT YÖNLÜ
-- uygulanır: engelleyen engellenenin yorumlarını görmez, engellenen de
-- engelleyenin yorumlarını görmez. Böylece engel, karşı tarafa "seni
-- engelledim" diye ilan edilmeden taciz zincirini keser.
create table if not exists public.user_blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  -- Kimse kendini engelleyemez.
  constraint user_blocks_not_self check (blocker_id <> blocked_id)
);
create index if not exists idx_user_blocks_blocked on public.user_blocks (blocked_id);

-- ---------------------------------------------------------------------------
-- 4) OTOMATİK GİZLEME — eşiği veritabanı uygular
-- ---------------------------------------------------------------------------
-- NEDEN VERİTABANINDA: gizleme kuralı yalnız uygulama kodunda dursaydı,
-- bildirim başka bir yoldan eklendiğinde (bakım betiği, ileride bir yönetim
-- ekranı) eşik hiç çalışmazdı. Trigger, bildirimin nereden geldiğine bakmaz.
--
-- EŞİK: 3 FARKLI kullanıcı. Reddedilmiş ('ret') bildirimler sayılmaz; böylece
-- haksız bulunmuş bir bildirim dalgası yorumu tekrar gizleyemez.
--
-- Gizleme GERİ ALINABİLİR: bildirimler 'ret' olarak işaretlenirse yorum yeniden
-- görünür olur (aşağıdaki ikinci trigger). "Otomatik" demek "kalıcı" demek
-- değildir.
create or replace function public.moderation_autohide_comment()
returns trigger language plpgsql as $$
declare
  gecerli integer;
  hedef   bigint;
begin
  hedef := coalesce(new.comment_id, old.comment_id);
  select count(distinct reporter_id) into gecerli
    from public.comment_reports
   where comment_id = hedef and status <> 'ret';

  if gecerli >= 3 then
    update public.comments
       set hidden_at     = coalesce(hidden_at, now()),
           hidden_reason = coalesce(hidden_reason, 'otomatik: bildirim esigi')
     where id = hedef and hidden_at is null;
  else
    -- Eşiğin altına düşüldüyse OTOMATİK gizlemeyi geri al. Elle gizlenmiş
    -- (başka sebep yazılmış) yoruma DOKUNULMAZ.
    update public.comments
       set hidden_at = null, hidden_reason = null
     where id = hedef and hidden_reason = 'otomatik: bildirim esigi';
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;

drop trigger if exists trg_report_autohide_ins on public.comment_reports;
create trigger trg_report_autohide_ins
  after insert on public.comment_reports
  for each row execute function public.moderation_autohide_comment();

drop trigger if exists trg_report_autohide_upd on public.comment_reports;
create trigger trg_report_autohide_upd
  after update on public.comment_reports
  for each row execute function public.moderation_autohide_comment();

drop trigger if exists trg_report_autohide_del on public.comment_reports;
create trigger trg_report_autohide_del
  after delete on public.comment_reports
  for each row execute function public.moderation_autohide_comment();

-- ---------------------------------------------------------------------------
-- 5) RLS — VARSAYILAN RET (default deny)
-- ---------------------------------------------------------------------------
-- comments ve comment_likes de buraya dahildir. Bu tablolar migration düzeni
-- dışında oluşturulduğu için RLS durumları hiçbir dosyada kayıtlı değildi.
-- Burada açıkça açılıyor ve doğrulamaya giriyor. Backend service role ile
-- bağlandığı için uygulamanın davranışı DEĞİŞMEZ; değişen tek şey, publishable
-- anahtarla doğrudan erişimin artık reddedilmesidir.
alter table public.comments        enable row level security;
alter table public.comment_likes   enable row level security;
alter table public.comment_reports enable row level security;
alter table public.user_blocks     enable row level security;
-- Bilerek HİÇBİR policy yok: yalnız service role (backend) erişir.

-- ---------------------------------------------------------------------------
-- SALT-OKUNUR DOĞRULAMA (çalıştırdıktan sonra):
--   select relname, relrowsecurity from pg_class
--   where relname in ('comments','comment_likes','comment_reports','user_blocks');
--   -- Beklenen: 4 satır, hepsinde relrowsecurity = true
--
--   select tgname, tgenabled from pg_trigger
--   where tgname like 'trg_report_autohide%';
--   -- Beklenen: 3 satır, hepsinde tgenabled = 'O'
-- ---------------------------------------------------------------------------
