-- 011 — DENETİM KAYDI: yönetim panelinden yapılan her müdahale
--
-- NEDEN: panel artık yorum SİLİYOR, kullanıcı ENGELLİYOR ve premium
-- VERİYOR. Bunlar sonuçları olan işlemler; "bunu kim, ne zaman, neden yaptı"
-- sorusunun cevabı bir yerde durmalı. Engelleme kaydında zaten kim/ne zaman
-- var ama silme işleminde hiçbir iz kalmıyordu.
--
-- NE YAZILIR, NE YAZILMAZ
--  • YAZILIR: işlem türü, hedef (kullanıcı/yorum/kod), operatör e-postası,
--    zaman, kısa ayrıntı (sebep, gün sayısı gibi).
--  • YAZILMAZ: yorumun tam metni, e-posta dışında kişisel veri, IP, belirteç.
--    Denetim kaydı bir "gölge veritabanı" değildir; ne olduğunu söyler,
--    silinen içeriği geri getirmez.
--
-- SALT EKLEME: kayıt güncellenmez ve silinmez. Değiştirilebilen bir denetim
-- kaydı, denetim kaydı değildir.

create table if not exists public.admin_audit (
  id         bigint generated by default as identity primary key,
  at         timestamptz not null default now(),
  actor      text not null,              -- operatör e-postası
  action     text not null,              -- 'yorum-sil' | 'kullanici-engelle' | ...
  target     text,                       -- yorum id / kullanıcı id / kod
  detail     text not null default '',   -- kısa açıklama (sebep, gün, adet)
  ok         boolean not null default true
);
create index if not exists idx_admin_audit_at on public.admin_audit (at desc);
create index if not exists idx_admin_audit_action on public.admin_audit (action, at desc);

comment on table public.admin_audit is
  'Yönetim panelindeki müdahalelerin salt-ekleme kaydı. İçerik kopyası TUTMAZ.';

alter table public.admin_audit enable row level security;
