// ---------------------------------------------------------------------------
// MIGRATION MOTORU — backend açılışında otomatik, tek doğruluk kaynaklı.
// ---------------------------------------------------------------------------
// GARANTİLER (hepsi test/migration-runner-live.test.mjs içinde GERÇEK
// PostgreSQL 16'ya karşı kanıtlanır):
//
//  1. SIRA        Dosyalar 001 → 002 → ... sırasıyla uygulanır.
//  2. TEK KEZ     Başarıyla uygulanmış dosya bir daha ÇALIŞMAZ (defter kaydı).
//  3. ÇİFTE YOK   İki backend aynı anda açılsa bile migration İKİ KEZ uygulanmaz
//                 (PostgreSQL advisory lock — veritabanının kendi kilidi).
//  4. YARIM YOK   Her dosya + defter kaydı TEK transaction'dadır. Hata olursa
//                 PostgreSQL hepsini geri alır; yarım tablo/trigger kalmaz.
//  5. BÜTÜNLÜK    Uygulanmış bir dosya sonradan değiştirilirse SESSİZCE kabul
//                 edilmez; sistem durur ve hiçbir şey uygulamaz.
//  6. GİZLİLİK    Bağlantı bilgisi ne loga ne hata metnine yazılır (dbUrl.gizle).
//  7. FAIL-CLOSED Hata hâlinde `ok:false` döner; çağıran (server.js) worker ve
//                 scheduler'ları BAŞLATMAZ.
//
// KAPSAM DIŞI (bilinçli): Bu motor migration'ları GERİ ALMAZ (down migration).
// Geri alma, uygulanmış bir şemayı geriye döndürmek demektir ve bu projede
// "eski kayıt silinmemeli, kilitli snapshot içeriği değiştirilmemeli" kuralıyla
// çelişir. Düzeltme daima YENİ bir migration dosyasıyla yapılır.

import { hostname } from 'node:os';
import { createHash } from 'node:crypto';
import pg from 'pg';
import { calistirilacakIfadeler } from './sqlScan.js';
import { dosyalariOku, planCikar } from './plan.js';
import { baglantiYapilandirmasi, guvenliHata } from './dbUrl.js';

const { Client } = pg;

/** Defter tablosu — uygulanan her migration'ın adı, sırası, zamanı ve mührü. */
export const DEFTER = 'public.schema_migrations';

const DEFTER_SQL = `
create table if not exists ${DEFTER} (
  version     text primary key,
  filename    text        not null,
  checksum    text        not null,
  applied_at  timestamptz not null default now(),
  applied_ms  integer,
  applied_by  text,
  seq         bigint generated by default as identity
);
comment on table ${DEFTER} is
  'Uygulanan migration defteri. Satırlar SİLİNMEZ ve GÜNCELLENMEZ; her satır bir migration''ın adı, sırası, zamanı ve dosya bütünlük mührüdür.';
alter table ${DEFTER} enable row level security;
`;
// RLS açık + policy YOK ⇒ publishable/anon anahtarla erişim varsayılan olarak
// REDDEDİLİR. Deftere yalnız backend'in doğrudan veritabanı bağlantısı erişir.

/**
 * Advisory lock anahtarı — sabit metinden TÜRETİLİR (sihirli sayı değil).
 * PostgreSQL'in kendi kilidi olduğu için: süreç çökerse oturum kapanır ve kilit
 * kendiliğinden serbest kalır — asılı kilit kalmaz.
 */
const KILIT = (() => {
  const h = createHash('sha256').update('sportoto:schema_migrations:v1').digest();
  return [h.readInt32BE(0), h.readInt32BE(4)];
})();

const bekle = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * Atlanan ifadeleri insan diline çevirir. Atlama SESSİZ olmaz: neyin ve neden
 * çalıştırılmadığı her zaman loga yazılır.
 */
function atlananNotu(atlanan) {
  if (!atlanan.length) return '';
  const meta = atlanan.filter((a) => a.tur === 'psql-meta');
  const islem = atlanan.filter((a) => a.tur !== 'psql-meta');
  const parcalar = [];
  if (islem.length) {
    parcalar.push(`dosyanın kendi BEGIN/COMMIT'i motorun transaction'ına devredildi (${islem.length})`);
  }
  if (meta.length) {
    const satirlar = meta.map((a) => `${a.satir}. satır`).join(', ');
    parcalar.push(`psql komutu atlandı — SQL değil, sürücü çalıştıramaz (${satirlar})`);
  }
  return ` · ${parcalar.join(' · ')}`;
}

/** Doğrulayıcıyı çalıştırır ve sonucunu raporlar (yoksa sessizce atlanır). */
async function dogrula(client, dosyalar, dogrulayici, yaz) {
  if (!dogrulayici) return null;
  const sonuc = await dogrulayici(client, dosyalar);
  if (sonuc.ok) {
    yaz(`🔍 Şema doğrulandı — ${sonuc.ozet}.`);
  } else {
    yaz('⛔ ŞEMA DOĞRULAMASI BAŞARISIZ — beklenen nesneler eksik:');
    for (const e of sonuc.eksikler) yaz(`   • ${e}`);
  }
  return sonuc;
}

/**
 * Migration'ları uygular.
 *
 * @param {object} secenekler
 * @param {string} secenekler.klasor        migrations klasörü (mutlak yol)
 * @param {object} [secenekler.env]         ortam değişkenleri
 * @param {function} [secenekler.log]       satır yazıcı
 * @param {object} [secenekler.clientFabrikasi] test için bağlantı üreticisi
 * @param {function} [secenekler.dogrulayici]  (client, dosyalar) → doğrulama sonucu.
 *        Bağlantı hâlâ AÇIKKEN ve kilit hâlâ BİZDEYKEN çalışır; böylece başka bir
 *        kopya araya girip şemayı değiştiremez ve doğrulama gerçekten o anın
 *        fotoğrafını çeker.
 * @returns {Promise<{ok:boolean, durum:string, uygulanan:string[], mesajlar:string[], dogrulama?:object, hata?:string}>}
 */
export async function migrationUygula({
  klasor,
  env = process.env,
  log = console.log,
  clientFabrikasi = null,
  dogrulayici = null,
} = {}) {
  const mesajlar = [];
  const yaz = (satir) => { mesajlar.push(satir); log(satir); };

  const yapilandirma = baglantiYapilandirmasi(env);
  if (!yapilandirma.ok) {
    return {
      ok: false,
      durum: yapilandirma.sebep === 'tanimsiz' ? 'baglanti-yok' : 'baglanti-gecersiz',
      uygulanan: [],
      mesajlar,
      hata:
        yapilandirma.sebep === 'tanimsiz'
          ? 'SUPABASE_DB_URL tanımlı değil.'
          : 'SUPABASE_DB_URL bir PostgreSQL bağlantı dizesi değil (postgresql://... bekleniyor).',
    };
  }

  // 1) DOSYALARI OKU — veritabanına dokunmadan önce dosya düzeni sağlam mı?
  let dosyalar;
  try {
    dosyalar = dosyalariOku(klasor);
  } catch (err) {
    return { ok: false, durum: 'dosya-hatasi', uygulanan: [], mesajlar, hata: guvenliHata(err, env) };
  }
  if (!dosyalar.length) {
    yaz('ℹ️  Migration klasöründe dosya yok — yapılacak bir şey yok.');
    return { ok: true, durum: 'bos', uygulanan: [], mesajlar };
  }

  const client = clientFabrikasi ? clientFabrikasi() : new Client(yapilandirma.config);
  const uygulanan = [];
  let kilitAlindi = false;

  try {
    await client.connect();

    // Bir DDL bir tabloyu kilitlemek için sonsuza kadar beklemesin: hata verip
    // dursun ki yarım bir dağıtım sessizce asılı kalmasın.
    const kilitZamanAsimi = Number(env.MIGRATION_LOCK_TIMEOUT_MS) || 30_000;
    await client.query(`set lock_timeout = ${Number(kilitZamanAsimi)}`);

    // 2) KİLİT — "iki backend aynı anda" durumunun tek gerçek çözümü.
    // Kilit VERİTABANINDA tutulur; hangi sunucuda kaç kopya çalıştığından bağımsızdır.
    const sure = Number(env.MIGRATION_LOCK_WAIT_MS) || 120_000;
    const bitis = Date.now() + sure;
    while (true) {
      const { rows } = await client.query('select pg_try_advisory_lock($1, $2) as alindi', KILIT);
      if (rows[0].alindi) { kilitAlindi = true; break; }
      if (Date.now() >= bitis) {
        return {
          ok: false,
          durum: 'kilit-alinamadi',
          uygulanan: [],
          mesajlar,
          hata:
            'Başka bir backend kopyası migration uyguluyor ve beklenen süre içinde bitmedi. ' +
            'Hiçbir şey uygulanmadı; bu kopya güvenli şekilde durdu.',
        };
      }
      yaz('⏳ Başka bir kopya migration uyguluyor — sıra bekleniyor…');
      await bekle(1000);
    }

    // 3) DEFTER — yoksa oluştur (kendisi de idempotent).
    // Defterin ÖNCEDEN var olup olmadığı önemlidir: yoksa ve şemada zaten
    // migration nesneleri varsa, bu "elle uygulanmış şemanın deftere alınması"
    // anıdır (bkz. devralma notu aşağıda). Sessiz geçilmez.
    const { rows: defterYoklama } = await client.query(
      `select to_regclass('${DEFTER}') is not null as var,
              to_regclass('public.bulletin_snapshots') is not null as sema_dolu`,
    );
    const ilkDefter = !defterYoklama[0].var;
    const semaZatenVar = defterYoklama[0].sema_dolu;
    await client.query(DEFTER_SQL);

    // 4) PLAN — kilidi aldıktan SONRA okunur; diğer kopya bitirmişse onun
    //    yazdığı satırlar da burada görülür ve tekrar uygulanmaz.
    const { rows: defter } = await client.query(
      `select version, filename, checksum from ${DEFTER} order by version`,
    );
    const { bekleyen, uygulanmis, sorunlar } = planCikar(dosyalar, defter);

    if (sorunlar.length) {
      for (const s of sorunlar) yaz(`⛔ ${s.mesaj}`);
      return {
        ok: false,
        durum: 'butunluk-hatasi',
        uygulanan: [],
        mesajlar,
        hata: sorunlar.map((s) => s.mesaj).join(' | '),
      };
    }

    if (!bekleyen.length) {
      yaz(`✅ Veritabanı şeması güncel — ${uygulanmis.length} migration zaten uygulanmış.`);
      const d = await dogrula(client, dosyalar, dogrulayici, yaz);
      if (d && !d.ok) {
        return { ok: false, durum: 'dogrulama-hatasi', uygulanan: [], mesajlar, dogrulama: d, hata: d.eksikler.join(' | ') };
      }
      return { ok: true, durum: 'guncel', uygulanan: [], mesajlar, dogrulama: d ?? undefined };
    }

    // DEVRALMA (bir kereye mahsus): şema daha önce ELLE uygulanmış (Supabase SQL
    // Editor) ama defter tutulmamış. Motor bu dosyaları "bekleyen" görür ve
    // TEKRAR çalıştırır. Bu güvenlidir, çünkü migration'ların tamamı yeniden
    // çalıştırılabilir (idempotent): tablo/index/trigger tanımları
    // `if not exists` / `create or replace` ile korunur, veri güncelleyen iki
    // ifade (003, 004) `where provenance_type is null` ile sınırlıdır — daha
    // önce sınıflandırılmış KİLİTLİ SNAPSHOT'LARA dokunmaz.
    // Bu özellik varsayılmaz, test/migration-runner-live.test.mjs içinde
    // GERÇEK veriyle ölçülür ("kilitli veri parmak izi değişmemeli").
    if (ilkDefter && semaZatenVar) {
      yaz('ℹ️  Şema daha önce elle uygulanmış ve defter yokmuş — mevcut şema deftere');
      yaz('ℹ️  alınıyor. Migration dosyaları yeniden çalıştırılacak; tanımlar');
      yaz('ℹ️  zaten var olduğu için değişiklik yaratmazlar ve kilitli kayıtlara');
      yaz('ℹ️  DOKUNULMAZ. Bu yalnız bir kez olur; sonraki açılışlarda defter dolu olur.');
    }

    yaz(`🚀 ${bekleyen.length} yeni migration uygulanacak: ${bekleyen.map((d) => d.surum).join(', ')}`);

    // 5) UYGULA — her dosya kendi transaction'ında; dosya + defter kaydı BİRLİKTE.
    const kimlik = (env.RENDER_INSTANCE_ID || hostname() || 'backend').slice(0, 64);
    for (const d of bekleyen) {
      const t0 = Date.now();
      const { ifadeler, atlanan } = calistirilacakIfadeler(d.icerik);

      try {
        await client.query('begin');
        for (const ifade of ifadeler) {
          try {
            await client.query(ifade.metin);
          } catch (err) {
            err.migrationSatir = ifade.satir;
            throw err;
          }
        }
        await client.query(
          `insert into ${DEFTER} (version, filename, checksum, applied_ms, applied_by)
           values ($1, $2, $3, $4, $5)`,
          [d.surum, d.dosya, d.ozet, Date.now() - t0, kimlik],
        );
        await client.query('commit');
      } catch (err) {
        // PostgreSQL rollback: bu dosyanın yaptığı HER ŞEY geri alınır.
        try { await client.query('rollback'); } catch { /* bağlantı düşmüş olabilir */ }
        const nerede = err.migrationSatir ? ` (dosyanın ${err.migrationSatir}. satırı civarı)` : '';
        yaz(`⛔ ${d.dosya} uygulanamadı${nerede} — tamamı geri alındı, veritabanı değişmedi.`);
        return {
          ok: false,
          durum: 'uygulama-hatasi',
          uygulanan,
          mesajlar,
          hata: `${d.dosya}${nerede}: ${guvenliHata(err, env)}`,
        };
      }

      const ms = Date.now() - t0;
      yaz(`   ✅ ${d.dosya} · ${ifadeler.length} ifade · ${ms} ms${atlananNotu(atlanan)}`);
      uygulanan.push(d.surum);
    }

    yaz(`✅ Migration tamamlandı — ${uygulanan.length} dosya uygulandı.`);
    const d = await dogrula(client, dosyalar, dogrulayici, yaz);
    if (d && !d.ok) {
      return { ok: false, durum: 'dogrulama-hatasi', uygulanan, mesajlar, dogrulama: d, hata: d.eksikler.join(' | ') };
    }
    return { ok: true, durum: 'uygulandi', uygulanan, mesajlar, dogrulama: d ?? undefined };
  } catch (err) {
    return { ok: false, durum: 'baglanti-hatasi', uygulanan, mesajlar, hata: guvenliHata(err, env) };
  } finally {
    try { if (kilitAlindi) await client.query('select pg_advisory_unlock($1, $2)', KILIT); } catch { /* yok say */ }
    try { await client.end(); } catch { /* yok say */ }
  }
}
